spring:
  datasource:
    url: jdbc:sqlite:db.sqlite
    driver-class-name: org.sqlite.JDBC
    username: sa
    password: password
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: file:media/,classpath:/static

  jpa:
    hibernate:
      ddl-auto: create
    database: h2
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    show-sql: true


jwt:
  secret: aaaabbbsdifqbvaesoioegwaaaabbbsdifqbvaesoioegwaaaabbbsdifqbvaes